
platform :ios, ‘8.1’
target 'Disconto' do

pod "VK-ios-sdk"
pod 'Fabric'
pod 'Crashlytics'
pod 'SDWebImage', '~> 3.7'
pod 'MXBannerView'
pod "CSStickyHeaderFlowLayout"
pod 'SVProgressHUD', '~> 2.0'
#pod 'YandexMobileMetrica', '2.7.0'
pod 'Google/Analytics'
#pod 'KxMenu'
pod 'NYTPhotoViewer', '~> 1.2'
pod 'GoogleMaps'
pod 'PEPhotoCropEditor', '~> 1.3'
pod 'ok-ios-sdk'
pod 'TTTAttributedLabel'
pod 'Facebook-iOS-SDK'
#pod 'ForceCuBeSDK'
pod 'CCTextFieldEffects', '~> 0.1'
pod 'APParallaxHeader'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'SnowFallingFramework', '~> 1.4'
pod 'AppsFlyerFramework'
pod 'AFNetworking'
#pod 'Realm'
pod 'SDVersion', '~> 4.2'
pod 'HTMLAttributedString'
pod 'ABLoader'
pod 'FBSDKLoginKit'

end
